# this workflow requires to provide JIRA webhook URL via JIRA_URL and JIRA_COMPONENT GitHub Secret
# read more: https://support.atlassian.com/cloud-automation/docs/jira-automation-triggers/#Automationtriggers-Incomingwebhook
# original code source: https://github.com/beliaev-maksim/github-to-jira-automation

name: Issues to JIRA

on:
  issues:
    # available via github.event.action
    types: [opened, reopened, closed]

jobs:
  update:
    name: Update Issue
    runs-on: ubuntu-latest
    steps:
      - name: Create JIRA ticket
        env:
           # put into env vars to properly escape special bash chars
           ISSUE_TITLE: ${{ github.event.issue.title }}
           ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
        run: |
          # Determine Bug/Enhancement
          if ${{ contains(github.event.*.labels.*.name, 'Bug') }}; then
            ISSUE_TYPE=bug
          else
            ISSUE_TYPE=story
          fi

          # send JIRA request

          # Canonical doesn't encourage discussions in JIRA on public project issues.
          # Thus, it is NOT recommended to put description in JIRA in order to push conversation to GitHub
          # if strongly required, then replace '--arg body ""' with the next line
          # --arg body "$ISSUE_DESCRIPTION"

          data=$( jq -n \
                  --arg title "$ISSUE_TITLE" \
                  --arg url '${{ github.event.issue.html_url }}' \
                  --arg submitter '${{ github.event.issue.user.login }}' \
                  --arg body "" \
                  --arg type "$ISSUE_TYPE" \
                  --arg action '${{ github.event.action }}' \
                  --arg component '${{ secrets.JIRA_COMPONENT }}' \
                  '{title: $title, url: $url, submitter: $submitter, body: $body, type: $type, action: $action, component: $component}' )

          curl -X POST -H 'Content-type: application/json' --data "${data}" "${{ secrets.JIRA_URL }}"
